name: Docker Image rain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Checkout docker
    - uses: actions/hello-world-docker-action@master
    - name: echo
      run: echo Hello, rain!
