name: Docker Image rain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/hello-world-docker-action@master
    - name: Build the Docker image
      run: ll 
